### ISSUE TITLE
How to debug why kafkajs instrumentation doesn't connect spans on a different service

### ISSUE THREAD

**Issue by royi-frontegg** [aspecto-io/opentelemetry-ext-js#229] opened 2022-06-05 06:13 UTC
Hi guys,
I'm having some issues with several services that consume kafka messages but creates a new trace instead of connecting it to an existing one. This is not the case for all services, where the instrumentation is working as expected.
I'm using 0.27.X libs on all services which makes everything even more confusing.
How can I debug the issue? 

Thank you

**Comment by blumamir** [comment] 2022-06-05 06:34
> Hi guys, I'm having some issues with several services that consume kafka messages but creates a new trace instead of connecting it to an existing one. This is not the case for all services, where the instrumentation is working as expected. I'm using 0.27.X libs on all services which makes everything even more confusing. How can I debug the issue?
> 
> Thank you

Hi Royi,
Are consuming messages from kafka as a batch? if so then the behaviour [follows the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#batch-receiving).
The issue is that there are many messages (possibly produced by different traces) all "fan-in" into a single operation at the consumer, so there is no one trace to continue. The instrumentation opens a new trace and uses links to the producer context.

**Comment by royi-frontegg** [comment] 2022-06-05 14:39
@blumamir no.. I'm using the "eachMessage" api

**Comment by blumamir** [comment] 2022-06-06 10:41
I would suggest printing the Kafka headers to make sure they are received correctly on the consumer side. Is the client that produces the messages to Kafka also in nodeJS?
Can you share a minimal setup that reproduces the issue?

**Comment by blumamir** [comment] 2022-08-18 06:58
Closing the issue. Please reopen if this is still relevant :)

**Closed by blumamir** 2022-08-18 06:58 UTC
